### ISSUE TITLE
Registrator

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaPlots/PlotReferenceImages.jl#40]
@JuliaRegistrator register()

**Comment by SimonDanisch** [comment]
@JuliaRegistrator register()

**Comment by daschw** [comment]
Don't we need tests for that?

**Comment by SimonDanisch** [comment]
do we ? :D lets see^^

**Comment by SimonDanisch** [comment]
After all there isn't much to test here ;)

**Comment by SimonDanisch** [comment]
Nevermind, I got a better idea! Lets just download sources of tags!
